- name: copy wmi*.msi into tmp file
  win_copy:
      src: "wmi_exporter-0.2.7-amd64.msi"
      dest: c:\Temp
  when: ansible_os_family="Windows" and ansible_architecture = "64-bit"

- name: copy wmi*.msi into tmp file
  win_copy:
      src: "wmi_exporter-0.2.7-386.msi"
      dest: c:\Temp
  when: ansible_os_family="Windows" and ansible_architecture = "32-bit"

- name: install i386 wmi-exporter for 32bit windows
  win_package:
      path: c:\Temp\wmi_exporter-0.2.7-386.msi
      state: present
  when: ansible_os_family="Windows" and ansible_architecture = "32-bit"

- name: install x64 wmi-exporter for 64bit windows
  win_package:
      path: c:\Temp\wmi_exporter-0.2.7-amd64.msi
      state: present
  when: ansible_os_family="Windows" and ansible_architecture = "64-bit"

