- name: check pingable of host
  ping: 
- name: check node_exporter package status
  apt:
      name: nodedaemon-exporter
      state: present
- name: check supervisor package status
  apt:
      name: supervisor
      state: present
- name: check node_exporter process status
  supervisorctl:
      name: node_exporter
      state: restarted 

